language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
deploy:
  provider: npm
  email: zkwentz@gmail.com
  api_key:
    secure: OhObU3/dY6p0NkD1MSCxWF73/UHJOGdo3q8Bh/Gq6T3NCS4wksjsLkzElUrG+9kuhayGFrjtFTMXMtLwZuAb+l+WZ2zUrMbGNBdYBdrJc6cVa985M8RiF3epHMkT362ihrYcBncB3zns0bjS7w1xTD546vMKAYF5U9UiHRTAwYXJR4xDXnJ3RVzI/avkYan8nVnQ9aEmsew26wBEATnhZNxpco6N75ljWpeT46aPSTVNpI7/0/ia2DP1mUC1YfwytNsJrknEi9MYCV6QAdTpvgUlNosQ8sOcFrKPquHE+JFJLe7jAfrwDRnFaYiPbStH/KkkhqN5YpM7+Al/6zks5c8WlNXMMg3VoH122h/HZLY1/0T94ZwNlrIAy8+HvYYnf61a3Iganz8IzhFK4lzIqPht7UTudD3jB2ULjo3Xys6jVKKzjAsg+ZKrHUHaLaDJdWl6FFa+i9SItaJYGlVTkajsOWKKGPgDioGwOnjVCjRhe3PfkJ8XcleIehHFWEbSdQZvKM8E0zWmvmCf6yZjDW2SEuOj4mWWRbfdclrchbgvYgpm+lLB5A3Ro2TjTo6fLYIHK/heY4VNr+HwLPYA9EwLkvBjfocMmcj3j1s78RfL5izZjiFAozqwPF0bxwwKsZ2VqPjgD6WJi1lQT63pEOG1FKgXYM4oDb0NmMTBgMk=
  on:
    tags: true
    repo: zkwentz/ember-cli-controller-isactive
